spring.application.name=Ecom-Store
spring.datasource.url=jdbc:mysql://localhost:3306/dialeradb?createDatabaseIfNotExist=true
spring.datasource.username=Rameesha
spring.datasource.password=Rrroom14@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=imaan2726@gmail.com
spring.mail.password=zooiuvzzrsbxrunm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

admin.notification.email=imaan2726@gmail.com

jwt.secret=76754gf38rthf8746732hejdfvg72382-uiwrt1276472846hsfv
jwt.expiration=8640000

